version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: news_local_api
    container_name: api_news
    depends_on: 
      - mongo
    env_file:
      - ./.envs/.local/.mongo
    volumes:
      - ./news:/news
    ports:
      - "8000:8000"
    command: /start

  scraper:
    build:
      context: .
      dockerfile: ./compose/local/scraper/Dockerfile
    image: news_local_scraper
    depends_on:
      - mongo
    env_file:
      - ./.envs/.local/.mongo
    volumes:
      - ./scraper:/scraper
    command: ['python', 'run.py']

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    env_file:
      - ./.envs/.local/.mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example